default_platform(:ios)

before_all do |lane, options|
  FileUtils.mkdir_p("../build/") unless File.exist?("../build/")
end

platform :ios do
  desc "Run the unit tests."
  lane :tests do
    # Use xcodebuild directly as Fastlane's scan does not yet support pure SPM projects 
    # See https://github.com/fastlane/fastlane/discussions/17362

    xcodebuild(
        scheme: "CrowdNotifierSDK-Package",
        xcargs: "-sdk iphoneos -destination 'platform=iOS Simulator,name=iPhone SE (2nd generation)' -resultBundlePath ./build/testresults.xcresult test",
        buildlog_path: "./build/"
    )

    trainer(
        output_directory: "./build/",
        path: "./build/",
        fail_build: false)
  end

  desc "Run Swiftlint."
  lane :codequality do
    swiftlint(
      mode: :lint,
      path: "./Sources/",
      output_file: "./build/swiftlint.result.json",
      strict: true,
      raise_if_swiftlint_error: true,
      reporter: "sonarqube"
    )
  end
end