name: Codequality

on:
  push:
    branches: [ master, develop ]
  pull_request:

jobs:
  codequality:
    name: Codequality
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - name: Switch to Xcode 12.4
      run: sudo xcode-select --switch /Applications/Xcode_12.4.app

    - name: Fastlane
      run: fastlane codequality

    - name: Archive logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: codequality-logs
        path: build
      
